---
- name: Install APT repositories
  apt_repository: repo='ppa:ubuntugis/ppa' state=present
  become: true

- name: Install APT dependencies
  apt: name={{ item }} state=present update_cache=true
  with_items:
    - python-pip
    - gdal-bin
  become: true

- name: Install Python modules
  pip: name={{ item }} state=present
  with_items:
    - flask
    - numpy
    - scipy
    - sklearn
    - pandas
    - nltk
    - boto3
    - statsmodels
    - osmapi
  become: true

- name: Make sure the app folder is created
  file: path=/opt/my_app state=directory owner=ubuntu group=ubuntu mode=0755
  become: true

- name: Put app codes in place
  synchronize: src=../../../../my_app dest=/opt/

- name: Configure supervisor script for app
  template: src=supervisor.conf dest=/etc/supervisor/conf.d/my_app.conf
  become: true
  notify: Reload app supervisor
